### ISSUE TITLE
BSP75N C114056  SOT-223 POWER DISTRIBUTION SWITCHES ROHS

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#111]
is BSP75N  an option for us as injector driver?

is it compatible with current injector driver?

![image](https://user-images.githubusercontent.com/48498823/140629612-4504697d-3d1f-4890-bd49-32183998b024.png)

there are four related lines

https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=BSP75N

![image](https://user-images.githubusercontent.com/48498823/140629656-bf5cc70d-e98c-4690-a3c8-c1bec5aa9f39.png)

**Comment by rusefillc** [comment]
@andreika-git @mck1117 @qwerty-off?

**Comment by rusefillc** [comment]
We've mentioned BSP76 previously but not BSP75N

**Comment by rusefillc** [comment]
look they even say solenoid!

![image](https://user-images.githubusercontent.com/48498823/140629730-375055ed-6d16-4514-81a3-f4032819ca20.png)

**Comment by rusefillc** [comment]
low current rating? :(

![image](https://user-images.githubusercontent.com/48498823/140629802-9d62e416-b89c-462d-ad12-e95f81faa4e9.png)

**Comment by mck1117** [comment]
That's too low for an injector or VVT.

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/wiki/module-output#parts-options
