### ISSUE TITLE
resistors around TC4427

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#118]
there is an opinion that more resistors are needed to save stm32

https://github.com/rusefi/rusefi/issues/3558

![image](https://user-images.githubusercontent.com/48498823/143092590-7beaeedc-4e07-457b-8907-4d89b232ab0c.png)

**Comment by rusefillc** [comment]
we suspect that this board had wild alternator spikes due to bad PID settings this might have contributed to problem

**Comment by rusefillc** [comment]
@mck1117 do we have similar RC on any other HW?

**Comment by mck1117** [comment]
Proteus and MRE both have it on their ignition/pushpull outputs.

**Comment by mck1117** [comment]
Actually I take that back - Proteus/MRE have pulldown resistors on the input side, but no series resistor.  They do, however, have a resistor on the output, also absent from Hellen.

![image](https://user-images.githubusercontent.com/568254/143506218-de69aaf3-f4aa-4eb6-a347-1c2747440266.png)

**Comment by andreika-git** [comment]
All Hellen boards also have pull-down resistors:
![image](https://user-images.githubusercontent.com/15104768/143542335-2db130e7-da73-4f8a-8ee1-669bfda72987.png)
But no series resistors.

**Comment by andreika-git** [comment]
Done: output-0.3
https://github.com/andreika-git/hellen-one/commit/520bed03c96fdb8829f21b9a2b18f8b3528e3318
![image](https://user-images.githubusercontent.com/15104768/143561216-dc0950f9-b97e-42cf-9286-d4b64621d4e7.png)
