### ISSUE TITLE
alphax-2 chan ibom issue

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#129]
https://rusefi.com/docs/ibom/alphax_2ch-a-ibom.html is not well at least in terms of jumpers and Q* in the corner

**Comment by rusefillc** [comment]
Side note https://gitlab.com/kicad/code/kicad/-/issues/10427

**Comment by andreika-git** [comment]
Some improvements were made: https://github.com/rusefi/alphax-2chan/commit/abc5a8ebcc6c41277835404d8beb879a369020f5
![image](https://user-images.githubusercontent.com/15104768/149613349-8e8ce0f0-2c0f-442e-a0a1-b5c244bfb37d.png)
But still the "pcb" mode needs a solution for wrong VRML export...

**Comment by andreika-git** [comment]
These commits contain the fix:
https://github.com/rusefi/alphax-2chan/commit/92fd5b5673dd5f4d12652d63d3fbda9657d96fd1
https://github.com/rusefi/alphax-2chan/commit/91e5ef016314e5647f6cc83b78ca2cee16ba263e
https://github.com/rusefi/alphax-2chan/commit/e9ce4495ee0449a3d88da4ec8a895c0278310a68
https://github.com/andreika-git/hellen-one/commit/f4a77038f289d80cee1175e8621dbb18583f7e1a
https://github.com/andreika-git/hellen-one/commit/87ed08e89f21c9c0805b78007eb04ac6608884f4
https://github.com/andreika-git/hellen-one/commit/15edebca0159f1d3145b61e1e0d41f87b1c1dd0e
https://github.com/andreika-git/hellen-one/commit/fcb62a786cf2ece60d0c5d966575e693b0ccbd8e
https://github.com/andreika-git/hellen-one/commit/8a70b219a5906cba4a520e92416ce6ff446d2ccc
https://github.com/andreika-git/hellen-one/commit/8cc300512e82af056219ab5d529753e834c27296

**Comment by rusefillc** [comment]
progress was made
