### ISSUE TITLE
create WBO module

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#13]

**Comment by rusefillc** [comment]
@andreika-git please provide a status update

**Comment by andreika-git** [comment]
Status update: The initial files for the WBO module were generated and uploaded to the repo. 
Also we need to create AD symbol+footprint for this module. 
Also we need to add it to _any_ board and test if it merges correctly. 
Finally, we'll need to test it on a real hw.

**Comment by andreika-git** [comment]
Exported CPL coords for WBO module are wrong (non-zero offset).

**Comment by andreika-git** [comment]
Fixed in Kicad by doing this:
![image](https://user-images.githubusercontent.com/15104768/111915838-e0fc2500-8a80-11eb-832a-e86feff5bcaa.png)
