### ISSUE TITLE
JLC is not happy with ign8 

### ISSUE THREAD

**Issue by abelom** [andreika-git/hellen-one#135]
See https://github.com/rusefi/hellen128merc-issues/issues/51 there is a report of single holes becoming slightly offset pairs of holes

**Comment by rusefillc** [comment]
@andreika-git was this fixed by https://github.com/andreika-git/hellen-one/commit/8024162d1d9963e9ef1200ac4bfcfc9189046d0e ?

**Comment by andreika-git** [comment]
Yes
