### ISSUE TITLE
Can we power VR discrete from sensor supply +5VA

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#138]
Since we control +5VA for low consumption sleep would the simplest way to sleep VR discrete be powering it off +5VA?

**Comment by rusefillc** [comment]
@mck1117

**Comment by mck1117** [comment]
DO NOT power any internal devices off of the external 5V sensor supply bus.  Remember, the external 5v sensor bus has the design specification of allowing short circuits to any external voltage on a car.

**Comment by rusefillc** [comment]
@mck1117 says "vr discrete requirement is 5v does not go above 5v"

@andreika-git i think we have the case of me failing to be the messenger. I strongly suspect that at the moment my not great questions is causing @mck1117 not to answer the real question you are after.

@andreika-git would you like to ask a better specific question?

**Comment by rusefillc** [comment]
@mck1117 says "the 5v rail does not need to be super duper mega accurate, using a second tls115 for internal 5v things would be fine"

**Comment by rusefillc** [comment]
8chan has two different tls115

![image](https://user-images.githubusercontent.com/48498823/215279877-37688f8f-84bc-4185-9b07-53a5b9d31996.png)
