### ISSUE TITLE
create MAX992x module

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#14]
We need a single channel VR decoder module based on MAX992x

Let's reuse a piece of https://github.com/mck1117/proteus/ if MAX9924 or Frankenso is MAX9926 as a reference schematics

**Comment by rusefillc** [comment]
@andreika-git  shall we name this module 'vr-max9924" or something else?

**Comment by andreika-git** [comment]
I think we should name it "vr". 
We will have 2 options for vr sensors: the built-in one already used in Hellen81 (tested on a real car, but needs more testing) and this new module "vr", that's enough IMHO.

**Comment by rusefillc** [comment]
there is a chance of 9926 later if we need dual channel VR
how do we distinguish between MAX and adc-based?

**Comment by andreika-git** [comment]
1) Then why not use 9926 instead of 9924 in "vr" module and make it dual-channel by default, like it was in many previous boards (Frankenso, Prometheus)?
2) Or we can use two 9924 modules for 2 channels
3) adc-based means no "vr" modules, and max-based means "vr" module - it's easy to distinguish

**Comment by andreika-git** [comment]
Frankenso schematic:
![image](https://user-images.githubusercontent.com/15104768/109924761-75b50380-7cc9-11eb-8773-36d31316644a.png)

**Comment by rusefillc** [comment]
Let's go with 9926

**Comment by rusefillc** [comment]
@andreika-git what is the status of this issue?

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/commit/1248a41075824e934b88539bab09130ec319cad4 could be related

**Comment by andreika-git** [comment]
The vr module was created (https://github.com/andreika-git/hellen-one/commit/1248a41075824e934b88539bab09130ec319cad4) but not used in any of the boards yet, and neither verified nor tested.
