### ISSUE TITLE
unattended bin/check_all.sh with continuous integraion

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#159]
Hellen-one is an amazing framework leveraging pretty hard code python3.8 scripts with tons of dependencies

We need a reliable way to have the amazing script working at least on ubuntu (meaning WSL). One day we shall fix cygwin and debian but for right now let's focus at least on WSL and default WSL is Ubuntu right?

@andreika-git has created an amazing bin/check_all.sh script which does a lot in terms of environment validation but has a few issues

A proper solution would be GHA continuous integraion.

Most immediate problem: amazing script asks user for confirmation for each install, we need an "AUTO or ALL" option to have unattended setup

**Comment by andreika-git** [comment]
Relevant commits:
https://github.com/andreika-git/hellen-one/commit/0e1afc32efba4949aedc41a6467ffb92d9ee6cd0
https://github.com/andreika-git/hellen-one/commit/f8d48511a9b1143a13360cc11b8c8947fcaaffc7

**Comment by rusefillc** [comment]
Docker has address this?
