### ISSUE TITLE
Module rotation

### ISSUE THREAD

**Issue by andreika-git** [andreika-git/hellen-one#16]
Some boards may require module rotation. We need to implement it in our board merging script (see gerbmerge: *rotated90)

**Comment by andreika-git** [comment]
https://github.com/andreika-git/hellen-one/commit/8dc935c2d491ab26e5ff0778f1e41fcedcf005dd

**Comment by andreika-git** [comment]
It seems that module rotation now works for WBO gerbers!
![image](https://user-images.githubusercontent.com/15104768/111915370-94afe580-8a7e-11eb-9be1-bc8381027435.png)

Still need to implement VRML rotation, though.

**Comment by rusefillc** [comment]
The critical part of this change is done, VRML is not on the critical path
