### ISSUE TITLE
typo? high1 shared pin with what low?

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#166]
https://github.com/andreika-git/hellen-one/wiki/module-output

![image](https://user-images.githubusercontent.com/48498823/172079666-7649b8e1-018e-495d-93e2-61eaf0300337.png)

**Comment by andreika-git** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/15104768/172158558-f2dfb30c-d98f-4f4d-8493-40aac6601cf9.png)
