### ISSUE TITLE
vr-discrete says MAX9142ESA+T is no more

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#170]
https://github.com/andreika-git/hellen-one/wiki/module-vr-discrete is asking for MAX9142ESA+T which seems to no longer exists

do we have JLC or findchips.com alternatives in stock? would we have to adjust gerbers for an alternative part?

**Comment by rusefillc** [comment]
@Qwerty-OFF can you please help?

@mck1117 FYI

**Comment by rusefillc** [comment]
Actually I can totally order more just not on JLC, so the priority goes down - still, would be nice to find a JLC alternative even if that would mean gerber adjustment

**Comment by Qwerty-OFF** [comment]
@mck1117 please check
TLV3202AIDR_C129325
TLV3702ID_C133808 (too slow?)

**Comment by rusefillc** [comment]
@mck1117 says

TLV3202 looks ok


TLV3702 is too slow
