### ISSUE TITLE
Expose more stm32 pins on mcu-144

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#171]
How come we have a few unconnected pins

![image](https://user-images.githubusercontent.com/48498823/181117658-3a2a7f8e-026e-4400-addd-f6d3b9ac5274.png)

![image](https://user-images.githubusercontent.com/48498823/181117697-e4f1b82c-77e0-4a06-82db-e96f664ab3eb.png)
![image](https://user-images.githubusercontent.com/48498823/181117712-be767893-a6ef-4af9-a05d-c5b7d8c0c12e.png)
![image](https://user-images.githubusercontent.com/48498823/181117744-b73ff84f-758a-46e0-9805-9f0b21590821.png)

![image](https://user-images.githubusercontent.com/48498823/181117821-45849f45-5554-48c9-b13f-85d7c1643eab.png)

**Comment by rusefillc** [comment]
@andreika-git can you please remind? is this related to 2 layer limitation of the module or else?

**Comment by andreika-git** [comment]
> @andreika-git can you please remind? is this related to 2 layer limitation of the module or else?

Related to very dense component layout and lots of vias (which are pass-through all layers). 
4 layers version *could* possibly help to expose some of the hidden pins, but no guarantees...

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-4chan/issues/51

**Comment by rusefillc** [comment]
[8chan ](https://github.com/rusefi/alphax-8chan/issues/22) is asking for this change on MCU 0.7

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/197035693-ea9396f8-17b7-4aaf-9356-8848d783ef58.png)

![image](https://user-images.githubusercontent.com/15104768/197035518-eda7cdd1-c44f-4c2e-8c75-2c4f17f13c95.png)

The new exposed pins are:
- IO5 = PG15
- IO6 = PD8
- IO7 = PF15
- IO8 = PE10
- IO9 = PF2 (not recommended! reserved for future Board-ID expansion)

Currently all 144 pins are used!

The mcu-0.7 module (176-pin) was also modified to support the new symbol/footprint (and the same pins).

**Comment by rusefillc** [comment]
or even remove it from footprint?
