### ISSUE TITLE
double-sided version of WBO with integrated CAN and option for external REF

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#176]
problem statement: fit more stuff by using double-sided assembly

WBO always goes with CAN

https://github.com/andreika-git/hellen-one/tree/master/kicad/modules/hellen1-wbo
combined with CAN transiever - see for instance https://github.com/rusefi/hellen154hyundai/
See https://github.com/andreika-git/hellen-one/tree/master/modules/can/0.1

can we reduce combined space by going double-sided?

**Comment by Qwerty-OFF** [comment]
Without changes in WBO module it is impossible, bottom side occupied by tracks.

**Comment by rusefillc** [comment]
Right, i mean to change the module

**Comment by Qwerty-OFF** [comment]
Is only CAN move to bottom or other WBO components also for minimization?

**Comment by rusefillc** [comment]
any component where it's reasonable for electrical reasons could go on the back side in order to reduce total rectangle size

@mck1117 FYI

**Comment by mck1117** [comment]
do we want to change random things, or seek some stability in the world?

**Comment by rusefillc** [comment]
@mck1117 please reduce noise.

if are looking for a clarification on reasons beyond what should already be available to you and obvious please just ask explicitly.

**Comment by rusefillc** [comment]
@Nadezhda-n можешь попробовать?

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/189

**Comment by rusefillc** [comment]
@Nadezhda-n получается первый шаг - это к kicad схеме WBO добавить AD схему CAN?

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/197765431-e78ab1f0-703d-468d-b0ff-9d6895ab69c1.png)
We need to add CANL, CANH, CANVIO on the module

**Comment by Nadezhda-n** [comment]
ok
![image](https://user-images.githubusercontent.com/99179773/198203704-d12d4a0d-2940-495e-8ef9-e31bc4ea77f3.png)
![image](https://user-images.githubusercontent.com/99179773/198203587-13a944ba-c073-41a7-a7fc-314b3af15f81.png)
