### ISSUE TITLE
WBO two modules to reuse voltage reference REF3033

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#189]
C130016 is one of the most expensive chips, when we have dual WBO can we share one REF3033 for two modules?

**Comment by rusefillc** [comment]
@mck1117 opinions?

**Comment by mck1117** [comment]
Sure, break out the vref pin to the module outside, tie them together, and omit all but one module's REF3x33.  BTW, REF3333 will also work in place of REF3033.

**Comment by rusefillc** [comment]
@Qwerty-OFF @Nadezhda-n I assume we have not done that yet? Is this a quick change to make to include into 8chan?

With MegaModule only MM would have REF while all WBO would not have REF.

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/206700280-c442ece0-4b35-423d-894f-4971fd2718d9.png)
