### ISSUE TITLE
WBO STM32 GPIO for GND routing

### ISSUE THREAD

**Issue by Qwerty-OFF** [andreika-git/hellen-one#194]
@mck1117
We connected two unused GPIO pins (PF0, PF1) to ground to improve the routing.
![image](https://user-images.githubusercontent.com/4116383/199833898-0b49d249-65f4-4767-b875-8530b34093d0.png)

**Comment by mck1117** [comment]
Looks OK to me. Those pins are already configured to be floating by the software.

**Comment by rusefillc** [comment]
@Qwerty-OFF let's add a comment on the schematic clarifying why GND

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/201068546-122a53bc-29d5-4176-8d01-39f2ef390223.png)
