### ISSUE TITLE
R132 is tricky let's persist knowledge

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#198]
@andreika-git 
Он для более правильного делителя напряжения, чтобы центральный уровень (2.5В) после делителя был на уровне центра

Есть это CRANK "сырой" VR, то тогда это важно. А если это выход с модуля vr-discrete, то тогда всё равно

Резистор хорош именно там где сейчас, потому что у нас есть программный детектор VR-сигнала, который и аналоговый, и цифровой (переключается)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/201488979-6b4681ff-4a52-47da-a369-2ca4d14c1a74.png)
