### ISSUE TITLE
power off issues including ULN2003 flyback diode: parasitic power from main relay

### ISSUE THREAD

**Issue by andreika-git** [andreika-git/hellen-one#2]
Problem statement: Unlike TLE6240 and other smart low-side drivers with active clamp protection, ULN2003 has a simple internal flyback diode connected to an external +12V power line. When the ECU power is off, the voltage is still present on the main relay coil (connected to the battery) and thus the V12PROT bus is powered via the flyback diode, causing parasitic power for ECU and also triggering the main relay.
The output module needs to be corrected to solve this issue.

The solution for the next revision: use an additional TVS for clamping the ULN2003 instead of the ECU power.

The temporary solution for Hellen72b:
1) Remove R314 (0.1 Ohms 1206) - to disconnect V12P from V12PROT:
![image](https://user-images.githubusercontent.com/15104768/108096261-74f55e00-7089-11eb-93b0-c5a21ea641c4.png)

2) Remove R310 and R312 - to disconnect push-pull drivers from V12PROT:
![image](https://user-images.githubusercontent.com/15104768/108096657-e59c7a80-7089-11eb-8b9c-1ff007b85654.png)

3) Connect these two pads to +12V - to reconnect the power of push-pull drivers:
![image](https://user-images.githubusercontent.com/15104768/108098432-05cd3900-708c-11eb-9ff9-b8a9ec7291a3.png)

**Comment by rusefillc** [comment]
things are better but still three issues, @stefansf FYI

1) https://youtu.be/OEqeKp4ilVw blink if #3 plugged after #2

2) things light up BRIGHT if #2, #4, #3 inserted & ignition turned on

3) ECU does not turn off on ignition OFF

**Comment by andreika-git** [comment]
Hellen72b has an additional issue with D49, you need to remove it too:
![image](https://user-images.githubusercontent.com/15104768/108167116-e0791300-70fd-11eb-8d12-95c621c68d45.png)

**Comment by rusefillc** [comment]
coil LEDs are ON when they should not be?
ECU does not turn off

https://youtu.be/yGyNm7tmKyg

https://youtu.be/wGY7qok-m8o

https://youtu.be/YMbyt41SUfI

**Comment by rusefillc** [comment]
Also related or different issue: random shut-off situation

1) turn IGN on, turn off within next few seconds: ECU shuts down instantaniously

2) turn IGN on, turn of after more than few seconds (still no cranking): ECU takes some time to shut off

3) major cranking attempts / after engine was running: ECU does not turn off

all these tests turning ON and OFF was happening with PC disconnected. there was some hot PC plugging and unplugging in test #3

**Comment by rusefillc** [comment]
Done?
