### ISSUE TITLE
Document CPL expectation

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#211]
Related to https://github.com/andreika-git/hellen-one/issues/209 - we shall spell out what is expected somewhere

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/wiki/scripts-howto

**Comment by andreika-git** [comment]
Updated [scripts-howto](https://github.com/andreika-git/hellen-one/wiki/scripts-howto).
