### ISSUE TITLE
WBO-0.4

### ISSUE THREAD

**Issue by Qwerty-OFF** [andreika-git/hellen-one#237]
@Nadezhda-n 
Сборка 8chan сломалась из-за R620 в wbo-0.4
`* Error! Comment mismatch for the part #C17168: 0 != DNP`
Поломка происходит когда в проекте есть компоненты с одинаковым LCSC кодом и разным поле Value.

Переходное отверстие земли попадает на дорожку WBO- при слиянии герберов, нужно исправить:
![image](https://user-images.githubusercontent.com/4116383/207463733-33cc8b79-fc8d-4558-822d-c851d887814e.png)
![image](https://user-images.githubusercontent.com/4116383/207463737-5194fbed-c213-4de0-8769-1ec9f54b2404.png)

**Comment by rusefillc** [comment]
Fixed by https://github.com/andreika-git/hellen-one/pull/239
