### ISSUE TITLE
VR-discrete 0.2 Gerber edge

### ISSUE THREAD

**Issue by Qwerty-OFF** [andreika-git/hellen-one#238]
@Nadezhda-n В герберах непонятный прямоугольник вокруг модуля
![image](https://user-images.githubusercontent.com/4116383/207466658-903fe180-0b24-4207-94a6-5644dd53de76.png)

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/pull/242

**Comment by rusefillc** [comment]
> Получается, что это лишнее

спасибо сделал https://github.com/andreika-git/hellen-one/issues/243
