### ISSUE TITLE
Root cause of VR-discrete 0.2 Gerber edge maybe documentation issue?

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#243]
See https://github.com/andreika-git/hellen-one/issues/238#issuecomment-1353523007

**Comment by Nadezhda-n** [comment]
Полагаю, что для модулей это не нужно, но, на самом деле, не понимаю, зачем это нужно для любых других плат :)
А так, да "Root cause of VR-discrete 0.2 Gerber edge maybe documentation issue?" - прямоугольник на всех герберах и есть край модуля, на пред версии, как и в других платах, его нет :)

**Comment by Qwerty-OFF** [comment]
Кикад когда-то переименовал эту галочку с "не рисовать край платы на всех слоях" на "рисовать край платы на всех слоях". Видимо из-за этого возникла путаница. В руководстве по сути все правильно, но не соответствует свежему кикаду.
![image](https://user-images.githubusercontent.com/4116383/207973642-361c8947-5e0d-48a0-9798-a7e2493d9250.png)

**Comment by Nadezhda-n** [comment]
> Кикад когда-то переименовал эту галочку с "не рисовать край платы на всех слоях" на "рисовать край платы на всех слоях". Видимо из-за этого возникла путаница. В руководстве по сути все правильно, но не соответствует свежему кикаду. ![image](https://user-images.githubusercontent.com/4116383/207973642-361c8947-5e0d-48a0-9798-a7e2493d9250.png)

Ха-ха
Спасибо :)
