### ISSUE TITLE
VR discrete issues

### ISSUE THREAD

**Issue by mck1117** [andreika-git/hellen-one#245]
https://github.com/rusefi/rusefi/issues/4874
https://github.com/rusefi/rusefi/issues/4922
and maybe https://github.com/rusefi/alphax-4chan/issues/84

Seems that TLV3202 instead of MAX9142 has slightly different behavior, and is susceptible to oscillation on the falling edge that can cause an early falling edge.

In bench testing, adding a 10nF capacitor across pins 4-5 (pin 5 to ground) solves the issue, but further testing required.  @ElDominio is going to try it on his real engines that have this issue.

**Comment by mck1117** [comment]
The bodge I did on the bench:
![B02B3E39-ACCA-4FF2-B069-012EC05C4233](https://user-images.githubusercontent.com/568254/210432652-2ca7e925-aa0c-479e-b82d-e56186891da5.jpeg)

**Comment by ElDominio** [comment]
Would I not have to put on at pin3 too? Since I see we're putting a cap across 2IN+ and GND, wouldn't one be needed between 1IN+ and GND too? just for my info

**Comment by rusefillc** [comment]
@Qwerty-OFF can you help with ^^^?

**Comment by ElDominio** [comment]
Yaris with 10nf cap across 4 and 5 still has issues

**Comment by ElDominio** [comment]
[changingtocamactivewithinvertyaaris.zip](https://github.com/andreika-git/hellen-one/files/10355843/changingtocamactivewithinvertyaaris.zip)

I changed from not using cam to using cam

**Comment by rusefillc** [comment]
@ElDominio please clarify

"VR discrete issue" not resolved 
or 
"VR discrete issue" impossible to test because of CAM issue 
or 
"VR discrete issue" resolved, now separate issue?

**Comment by mck1117** [comment]
he forgot to add a second cap to the cam channel, and is going to test on a rev E so he can get an SD log

**Comment by ElDominio** [comment]
Yaris
RevE with 10nF capacitors on TLV3202

[OsciLogandNormalLogwithcapsRevE.zip](https://github.com/andreika-git/hellen-one/files/10356445/OsciLogandNormalLogwithcapsRevE.zip)
[re_15.zip](https://github.com/andreika-git/hellen-one/files/10356446/re_15.zip)

**Comment by ElDominio** [comment]
![Uploading q4{840dbaa} (dc2579a1-796f-45ee-a709-273b7efd75f1 id=0x7f0a0401 tag=BaseCommentFragment) …]()

**Comment by mck1117** [comment]
Cap seems to have made an improvement to crank signal:

before on left, after on right

Left has very not-50% duty cycle, falling edge comes very soon after rising edge. Right has near 50/50 duty, which is expected for VR signal with many teeth (like a 36-2 crank)

![image](https://user-images.githubusercontent.com/568254/210910163-63a69b67-dde9-4629-bfb0-edd456aa58d0.png)

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/247 for actual change

let's start by improving newer 2 sided version? we might end up making improved one sided version as well I guess

**Comment by ElDominio** [comment]
We might need another cap according to @mck1117 , @rusefillc . Pending testing

**Comment by mck1117** [comment]
> We might need another cap according to @mck1117 , @rusefillc . Pending testing

the updated schematic has both caps, like the original little test board I did
