### ISSUE TITLE
vr-discrete 0.4: Add 10nF between GND and 2IN+

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#247]
Please take vr-discrete)/0.4 add one capacitor and make that vr-discrete)/0.3 (yes, we are skipping 0.3 for now we might use 0.3 for same fix for single sided design later)

See #245 for details, we need one capacitor added to schematics and gerbers

**Comment by rusefillc** [comment]
@Nadezhda-n can you take care of this?

**Comment by mck1117** [comment]
I am not yet 100% sure that’s the only change required to fix issues. We can go ahead and draft the change, but don’t commit to that yet.

**Comment by mck1117** [comment]
Go ahead and add a cap between pin 2 and ground (in addition to pin 5). I've never seen it happen on the top half, but it's theoretically susceptible to the same oscillation.

**Comment by mck1117** [comment]
WAIT a second, those caps were already present on the original design, why did they disappear on the hellen module!?!?!

Little test board I made:

![image](https://user-images.githubusercontent.com/568254/211141669-7b202de4-cb2c-44fa-bc5f-0ba50340c070.png)

Hellen module:

![image](https://user-images.githubusercontent.com/568254/211141682-ce7a70c7-e466-44fd-8b2b-3d388be44cb2.png)

notice C9/C10 are exactly what we need to add, but were already there

**Comment by rusefillc** [comment]
hellen1-vr-discrete is one of the few kicad-based modules https://github.com/andreika-git/hellen-one/tree/master/kicad/modules

**Comment by rusefillc** [comment]
@mck1117 please review and confirm if we can fab a batch of boards

**Comment by mck1117** [comment]
0.4 schematic looks OK
