### ISSUE TITLE
Any chance to make WBO module less weird?

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#251]
4.9 heater wires are "heater+" and "12 raw" is not that a bit confusing?

![image](https://user-images.githubusercontent.com/48498823/211666437-e9230393-dd98-4236-aeb8-9ee7510648f0.png)

Snippet of https://github.com/rusefi/rusefi_documentation/blob/master/Hardware/Hellen/hellen125honda-a-schematic.pdf

https://github.com/andreika-git/hellen-one/tree/master/modules/wbo/0.4

**Comment by rusefillc** [comment]
@mck1117 @dron0gus any ideas for at least footprint comments to reduce confusion?

**Comment by rusefillc** [comment]
Let's make a compatible wbo-0.4 change by adding kicad notes to the symbol:

"LSU_H-" add blue note "power GND"
"GND" add blue note "analog/digital"
"LSU_H+" add blue note "heater negative"

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/211926706-10727bf3-602e-49af-9441-14922c298572.png)
