### ISSUE TITLE
h64 CPL rotation

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#26]
![image](https://user-images.githubusercontent.com/48498823/114277790-b86da800-99fa-11eb-8777-1d13402ed727.png)

![image](https://user-images.githubusercontent.com/48498823/114277796-bc012f00-99fa-11eb-94a3-498085dc8a6d.png)

**Comment by andreika-git** [comment]
https://github.com/andreika-git/hellen-one/commit/6ed466df55011effc9942c4281bbaf00b0e35188
https://github.com/andreika-git/hellen-one/commit/46ce17a2ef54e39abf2cab8c6a52183a04fd5818

It's better now but still needs more thorough check:
![image](https://user-images.githubusercontent.com/15104768/114298278-3b0b6b80-9abe-11eb-8070-c117d3a29c26.png)

When reloaded, it shows overlay with the board image, but with some vertical offset:
![image](https://user-images.githubusercontent.com/15104768/114298363-ab19f180-9abe-11eb-9b39-7ca69b12c68f.png)

The whole component layer is shifted:
![image](https://user-images.githubusercontent.com/15104768/114298407-ef0cf680-9abe-11eb-82c9-3af8e5a6ec2a.png)

I don't know whether it's the JLC's bug or our bug... 

Also the USB connector is shifted horizontally (upper corner) - possibly wrong CPL origin set in the Kicad footprint.

**Comment by andreika-git** [comment]
Status update:
- gerber viewer coordinate test shows there's no noticeable vertical offset. Assuming that's JLC's bug
- USB connector footprint (Hellen-one-common Kicad lib) has wrong origin: it uses 1st pad center instead of component centroid.
