### ISSUE TITLE
4chan ibom issues - VR not happy on PCB view

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#266]
https://rusefi.com/docs/ibom/alphax_4ch-f-ibom.html

two pictures are offset
R753_2 is shifted against both pictures

![image](https://user-images.githubusercontent.com/48498823/221663114-fe6e5197-8ff0-46b4-b8bc-41a7bfdeaa26.png)

**Comment by andreika-git** [comment]
Something wrong with VRML export of vrdiscrete-0.4. Maybe the origin coordinates were wrong. We need to re-export VRML with zero origin.
