### ISSUE TITLE
Explicitly spell out low side driver large tab flexibility or lack of flexibility

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#268]
хочется чётко задокументировать на https://github.com/andreika-git/hellen-one/wiki/module-output, какие варианты мы поддерживаем

![image](https://user-images.githubusercontent.com/48498823/224889246-04b6582b-fb87-4eee-b2cb-5375b57772f3.png)

![image](https://user-images.githubusercontent.com/48498823/224889261-eb203859-0475-4970-89bc-cc7a8bf4ce8b.png)

потому что например в наличии дешёвый ZXMS6005DGTA (мы ранее использовали ZXMS6005SGTA)

**Comment by andreika-git** [comment]
Done
