### ISSUE TITLE
DNP CAN terminator on WBO

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#280]
when do we _EVER_ need 120R on hellen-one WBO module?!

**Comment by rusefillc** [comment]
@Nadezhda-n 120R between CANH and CANL please leave footprint but mark DNP so that BOM for module does not have it

**Comment by rusefillc** [comment]
@Qwerty-OFF are we good to close?

**Comment by Qwerty-OFF** [comment]
Yes
