### ISSUE TITLE
Full skip of BOM lines without JLC PN

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#287]
https://github.com/rusefi/hellen125honda-issues/issues/41 U2 is populates while 
```
"BTS4175SGA","U2","SO8",""
```

looks like such lines should not be in BOM at all

**Comment by rusefillc** [comment]
![WhatsApp Image 2023-04-03 at 15 48 57](https://user-images.githubusercontent.com/48498823/229615458-3ff01857-4bec-4542-985f-59478ee2ae58.jpg)

**Comment by rusefillc** [comment]
could also be https://github.com/rusefi/hellen121vag/issues/79

**Comment by andreika-git** [comment]
If we skip BOM lines without JLC PN, then iBOM will be missing these lines! If we really want it, then we need separate BOM files for JLC and iBOM (and an additional script to create the truncated file). If we want to leave the JLC BOM file name as is (eg. hellenxxx-x-BOM.csv), then we need to come up with a name for the 'compete' iBOM file. Any ideas?

**Comment by rusefillc** [comment]
Great point!

Let's keep current file as is and have a script to produce new BOM-JLC file?

**Comment by andreika-git** [comment]
OK, we'll create a new board/xxx-BOM-JLC.csv file and move the current file to board/misc/xxx-BOM.csv

**Comment by andreika-git** [comment]
Done
