### ISSUE TITLE
hellen72: RED and BLUE LEDs on MCU module constantly ON

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#3]
With wrong MRE firmware RED "critical" was not ON

With proper Hellen firmware red and blue LEDs are constantly ON while TS and console shows no critical error?

**Comment by andreika-git** [comment]
All 4 LEDs work in inverted mode. When the pin is "0", the LED is on.

**Comment by rusefillc** [comment]
is that a feature or a bug?

**Comment by andreika-git** [comment]
It's more like a taste preference. Or "holy war" :) 
It origins from old TTL logic gates, where source current has higher limits than sink current, also it slightly offloads the mcu power and makes it less noisy (the "load" current flows only to the ground).

**Comment by rusefillc** [comment]
I hope that's not insanity

**Comment by rusefillc** [comment]
fixed in SW
