### ISSUE TITLE
power_12and5V: self-documentation on schematics

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#300]
* does power_12and5V has a "reverse polarity protection" group of components? can we mark relevant functional area?
* does power_12and5V has a "input filtering" group of components? can we mark relevant functional area?

**Comment by rusefillc** [comment]
если только прояснение на схеме - то ревизию можно оставить как есть?

**Comment by Qwerty-OFF** [comment]
<img width="752" alt="image" src="https://github.com/andreika-git/hellen-one/assets/4116383/d8112555-7381-4633-a0a1-4d95d48a3ced">
Ревизию не менял
