### ISSUE TITLE
create-board.yaml is being copy-pasted and that's not cool

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#306]
At the moment too many repos which use hellen-one framework are copy-pasting same create-board.yaml file

That's not ideal since even the create-board.yaml sometimes needs to be improved. Do we have any ways to reuse?

**Comment by rusefillc** [comment]
@chuckwagoncomputing what is the right way?

I can only think of reducing the impact by merging four shell scripts into one .sh script - and even that would reduce usability

**Comment by chuckwagoncomputing** [comment]
OK, now we've got only a tine create-board.yaml to copy-paste. I don't think we can do better than that.
