### ISSUE TITLE
Command line gerber export touches project files

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#307]
https://github.com/rusefi/hellen88bmw/commit/6149333b9ca89f442df8c9704b6ae35eb649b11c has touched .kicad_pro file

Do we have any concerns or do we keep thing as is?

**Comment by rusefillc** [comment]
One potentially negative consequence I can think of - at the moment we install _latest_ kicad thus at any moment of time fresh GHA might invoke latest and greatest and overwrite the file. This might well be bad timing forcing engineer to update his local install. @chuckwagoncomputing @Qwerty-OFF @andreika-git what do you think?

**Comment by chuckwagoncomputing** [comment]
Yes this should be fixed
