### ISSUE TITLE
h72 schematics usability

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#31]
![image](https://user-images.githubusercontent.com/48498823/115564153-36953e80-a286-11eb-8472-0de65c8375fa.png)

That's very confusing.

Do we have two different "in_knock" here - module internal "in_knock" pad and h72 frame "in_knock" net? 

If those are in fact two different entities having same name I would suggest to change the naming convention to avoid the confusion. I like the "raw" for inputs from connector, maybe "mcu_knock" for all nets between MCU and modules?

**Comment by andreika-git** [comment]
IMHO this should belong to https://github.com/rusefi/hellen72/issues/

**Comment by rusefillc** [comment]
I bet that's a hellen-one pattern not an issue specific to any board

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/115868850-b74e6900-a445-11eb-80a9-e8c6da6f44f6.png)

**Comment by rusefillc** [comment]
👍
