### ISSUE TITLE
WBO module needs SWD exposed as side pads on the module

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#32]
very few people have TC2030 plug

to increase usability we would need SWD as a 2.54mm header 

we do not want to add  2.54mm header on the WBO module due to space constraints, we want SWD exposed as side pads on the module so that specific board could do whatever

**Comment by rusefillc** [comment]
not sure how standard is this https://wiki.paparazziuav.org/wiki/STLink

**Comment by rusefillc** [comment]
https://github.com/rusefi/hw_microRusEfi/raw/master/compatible_ST-LINK_V2.jpg is the fake v2 we use on microRusEFI

**Comment by mck1117** [comment]
Do we need availability? 99% of people with MRE/Proteus don't have any programmer. We only need programming interface for "factory programming"

**Comment by rusefillc** [comment]
A number of boards are open source, also while 042 is poorly available there is too much of a chance of units shipped without 042

**Comment by rusefillc** [comment]
Done
