### ISSUE TITLE
MM100

### ISSUE THREAD

**Issue by Qwerty-OFF** [andreika-git/hellen-one#326]
Из модуля торчит наружу:
8x IGN / 5В-выход для управления VND10
8x INJ / IO
8x PWM_OUT / IN
14x аналоговый вход (один из них превращается в CAN Wakeup)
2х цифровой вход через операционный усилитель (VSS, knock)
4х цифровой вход через триггер Шмидта
2x SPI / 8x IO / CAN2 + 2x IO + SPI
CAN
USB
I2C
2x UART / 4x IO
SWD
@rusefillc жду корректировок или одобрения

**Comment by rusefillc** [comment]
@Qwerty-OFF а почему knock цифровой?
всё очень позитивно
SWD наружу на грани пользы, но вероятно мало влияет на всю картину, так что пусть торчит.

**Comment by Qwerty-OFF** [comment]
Поправил, knock аналоговый, все остальное без изменений

**Comment by Qwerty-OFF** [comment]
@Nadezhda-n сделал схему, можно трассировать. Футпринт модуля ММ100 нужно будет сделать по ходу работ. Цель запихнуть все это в минимальные возможные габариты

**Comment by Qwerty-OFF** [comment]
@Nadezhda-n я добавил пару земляных отверстий в проекте чтоб починить DRC, подправил outjob.
Пофикси тут пад земли чтоб зазор по вертикали был 0.2мм
![image](https://github.com/andreika-git/hellen-one/assets/4116383/a9e8b7f9-e013-4e67-98c8-e5ed61dff196)
Все остальное выглядит хорошо

**Comment by Nadezhda-n** [comment]
![image](https://github.com/andreika-git/hellen-one/assets/99179773/c5dac039-d515-49ce-8f36-c251211e2c54)

**Comment by rusefillc** [comment]
@Qwerty-OFF надо заполнить https://github.com/rusefi/rusefi/commit/a1291cef18575ab7edc827957f991d7b20c49427 файлик теперь :)

**Comment by Qwerty-OFF** [comment]
Сделано
