### ISSUE TITLE
MM100: duplicate A21

### ISSUE THREAD

**Issue by Nadezhda-n** [andreika-git/hellen-one#329]
![image](https://github.com/andreika-git/hellen-one/assets/99179773/a84e44a9-87a5-4fde-b4eb-20c03a9059a6)

@Qwerty-OFF please explain in the scheme :)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/andreika-git/hellen-one/assets/4116383/edb5bb65-e407-4845-8093-e50a0d4f5ac2)
