### ISSUE TITLE
Dinput4 merge problem

### ISSUE THREAD

**Issue by Qwerty-OFF** [andreika-git/hellen-one#33]
hellen121vag board:
![image](https://user-images.githubusercontent.com/4116383/116309856-f49e5800-a7b1-11eb-9159-00945fbea6f8.png)

Dinput4 gerber:
![image](https://user-images.githubusercontent.com/4116383/116309816-e6e8d280-a7b1-11eb-9485-15e9cbdb52e4.png)

**Comment by andreika-git** [comment]
The problem was in the module outline layer (.GM15), it was not big enough to keep all gerber objects inside.
Please re-run the create script for all boards using dinput4.
