### ISSUE TITLE
mm100 option to reuse yellow and green LED as GPIO

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#335]
do we have space to expose green and yellow LEDs as GPIO on the footprint if we DNP those LEDs?

sibling of https://github.com/andreika-git/hellen-one/issues/334

**Comment by Qwerty-OFF** [comment]
Yes

**Comment by rusefillc** [comment]
@Qwerty-OFF let's do it!

**Comment by Qwerty-OFF** [comment]
Done
