### ISSUE TITLE
Error in gerber files with *rotated* modules on the bottom side

### ISSUE THREAD

**Issue by Qwerty-OFF** [andreika-git/hellen-one#337]
In 8chan-b and 8-chan-c, the WBO modules are placed on the bottom side of the board. There are artifacts on the top and bottom layers in the resulting gerber files. It seems that the artifacts are related to some issue with processing the rounded pads.
![image](https://github.com/andreika-git/hellen-one/assets/4116383/27566ce5-5b70-41fc-bcb0-15527b2cde43) ![image](https://github.com/andreika-git/hellen-one/assets/4116383/79b7db5a-b8b6-434b-b550-72bbf8249a78)

**Comment by andreika-git** [comment]
Fixed by https://github.com/rusefi/alphax-8chan/commit/2ebd618d90802731fe311708ef8f32424b1d1a04

**Comment by andreika-git** [comment]
![image](https://github.com/andreika-git/hellen-one/assets/15104768/2d9b7c05-82de-4cb9-b1a5-ec500346d15a)
