### ISSUE TITLE
CAN wbo trick did not work

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#34]
BeerMoney reports that WBO stm32 does not talk to main stm32 until can driver is desoldered

once can driver is desoldered CAN communication is happy

![image](https://user-images.githubusercontent.com/48498823/116551076-86e35080-a8c5-11eb-88ab-e528ea7e89f3.png)

**Comment by mck1117** [comment]
CAN trick *did* work, it just doesn't work if you also try and connect a real CAN bus to the same fake-CAN bus.
