### ISSUE TITLE
mm100 f7

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#341]
F7 gives us so much needed RAM
mm100 gives us size

how does https://jlcpcb.com/partdetail/Stmicroelectronics-STM32F765VGT6/C435845 look for mm100-f7?

**Comment by Qwerty-OFF** [comment]
Looks good
<img width="359" alt="image" src="https://github.com/andreika-git/hellen-one/assets/4116383/e9af060d-0495-491f-9808-aee4edad27f2">

![image](https://github.com/andreika-git/hellen-one/assets/4116383/bfdf9f22-edf0-4b7d-8990-757496cc83d5)

**Comment by Qwerty-OFF** [comment]
Done

**Comment by rusefillc** [comment]
@Qwerty-OFF можно ли мне добавить в https://github.com/andreika-git/hellen-one/blob/master/modules/mega-mcu100-f7/readme.md файлик

* STM32F777VIT6
* STM32F767VIT6
* STM32F765VIT6

?

**Comment by Qwerty-OFF** [comment]
Да, полный список пин-совместимых:
![image](https://github.com/andreika-git/hellen-one/assets/4116383/d9fb5e16-e445-4607-80a6-0e97e5b30193)
