### ISSUE TITLE
разжёвывалки на схемы

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#347]
* [x] упомянуть "TC2030 connector" на WBO без изменения версии
* [x] упомянуть "TC2030 connector" на mcu144 без изменения версии
* [x] упомянуть кнопки boot/reset на mcu144 без изменения версии

![image](https://github.com/andreika-git/hellen-one/assets/48498823/30c17107-c1a5-4ffb-9fa5-ae9f369a2afc)

![image](https://github.com/andreika-git/hellen-one/assets/48498823/e2e418e2-0605-40c5-b94a-e0b7be4f34a3)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/andreika-git/hellen-one/assets/4116383/24d258aa-9cc0-4b30-a201-9b6bc8a28380)
