### ISSUE TITLE
Wiki link broken power5 module

### ISSUE THREAD

**Issue by dynfer** [andreika-git/hellen-one#352]
When accessing the link we get the following error

![obraz](https://github.com/andreika-git/hellen-one/assets/102673508/02f51ad9-ee3a-48ff-966e-e9e155b69492)

https://github.com/andreika-git/hellen-one/wiki/module-power5

**Comment by rusefillc** [comment]
@dynfer please clarify where did you find that https://github.com/andreika-git/hellen-one/wiki/module-power5 link?

**Comment by dynfer** [comment]
> @dynfer please clarify where did you find that https://github.com/andreika-git/hellen-one/wiki/module-power5 link?

Its the link in the modules section on the main page of the wiki, also I've noticed the Power12and5 module is missing in the list where it does exists in the repository(readme.md)

**Comment by rusefillc** [comment]
thank you should be better now
