### ISSUE TITLE
alternatives to QMA7981 accelerometer

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#36]
QMA7981 not in stock

![image](https://user-images.githubusercontent.com/48498823/116703197-fe81b000-a997-11eb-8385-2f6b4138ad83.png)

is KXTJ3-1057 or KX023-1025 pin compatible?

![image](https://user-images.githubusercontent.com/48498823/116703482-57e9df00-a998-11eb-8da8-f1cf11e50d7e.png)

not sure if LIS2DW12TR is compatible pinout

![image](https://user-images.githubusercontent.com/48498823/116703097-de51f100-a997-11eb-84bc-3e9b70133079.png)

**Comment by andreika-git** [comment]
LIS2DW12TR is used for Hellen81a and Hellen72d
