### ISSUE TITLE
uaefi footprint IGN output comment

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#366]
в районе IGN хочется подписать инструкцию модификации платы

что-то типа "logic level outputs by default
to control dumb coils remove XXX and populate YYY"

**Comment by Qwerty-OFF** [comment]
В uaefi-c добавить подпись непосредственно на uaefi

**Comment by Qwerty-OFF** [comment]
С двух сторон
![image](https://github.com/andreika-git/hellen-one/assets/4116383/87846cb8-5616-4f99-9143-86a4c45e2e8a)
![image](https://github.com/andreika-git/hellen-one/assets/4116383/434ba0ea-af55-47df-81df-6f58279eaca3)
