### ISSUE TITLE
uaefi no longer weak?

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#367]
all LS are 1A and more now?

![image](https://github.com/andreika-git/hellen-one/assets/48498823/2815c9f3-bc03-4680-b2c4-d7dc7cb22013)

**Comment by Qwerty-OFF** [comment]
Yes
![image](https://github.com/andreika-git/hellen-one/assets/4116383/cd58a6c4-dbd5-47eb-a62d-4aa271de4a98)
