### ISSUE TITLE
NB2 tach HW magic. Maybe related to alternator.

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#39]
Someone please write this up?

**Comment by rusefillc** [comment]
CrazyStriker says remove Q313, R313 and D304

![image](https://user-images.githubusercontent.com/48498823/117037781-db773900-acd4-11eb-9e23-73f0ad681494.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/117094449-d399b200-ad31-11eb-8264-45e7eac5be5d.png)

**Comment by rusefillc** [comment]
Q313 removal has returned tachometer into my life

https://youtu.be/WFEwe_KtHW4

**Comment by Qwerty-OFF** [comment]
Maybe fix protection like it made in power12 module?
![image](https://user-images.githubusercontent.com/4116383/117183630-6db83380-ade0-11eb-8265-661ea6911e39.png)

**Comment by mck1117** [comment]
Either fix it like that, or just remove it entirely.  I don't understand the reasoning to keep it around if the one in power12 exists too.
