### ISSUE TITLE
no we do not support H7 at all

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#391]
Stm32H743zit6 should not be mentioned as any default on any 144 MCU or MM module

at this point let's go with F7 2MB as default, that's the most proper long term chip

STM32F767ZIT6 C90235

**Comment by rusefillc** [comment]
@Qwerty-OFF no need to bump versions, let's just manually edit BOMs for recent versions of both mcu and mega

**Comment by Qwerty-OFF** [comment]
Already fixed all BOM where I found H7

**Comment by rusefillc** [comment]
@Qwerty-OFF я ошибся в описании

C90235 было правильно

STM32F767ZG не правильно

STM32F767ZI правильно
