### ISSUE TITLE
diode for vvt and idle outputs

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#40]
Matthew Kennedy  4:48 AM
wait, vvt uses a single auips2041?

andreika  4:49 AM
yes

Matthew Kennedy  4:49 AM
did we quantify how much current the vvt solenoid pulls

CrazyStriker  4:49 AM
With clamping diode?

Matthew Kennedy  4:49 AM
no diode

andreika  4:49 AM
yes we did but I don't remember the numbers

Matthew Kennedy  4:49 AM
it needs one

CrazyStriker  4:50 AM
Oh shit
4:50
I see 1.4 amps continuous operation for the driver

Andrey  4:50 AM
vvt resistance was 7?

Matthew Kennedy  4:50 AM
yeah, that's what I saw
4:50
14 volts 7 ohms -> 2 amps
4:51
add that to the list of "did we even try"

andreika  4:51 AM
what's the duty cycle for vvt?

Matthew Kennedy  4:52 AM
iirc around 50% will hold cam position
4:52
then advance/retard either side

CrazyStriker  4:52 AM
That would explain why some chips whine

Matthew Kennedy  4:52 AM
what else is powered by your fuel pump relay

andreika  4:52 AM
then vvt should be fine

Matthew Kennedy  4:52 AM
is that also the vvt by chance?

CrazyStriker  4:52 AM
34% for hold and +-15% dynamic
4:53
The FP relay only powers FP
4:53
VVT goes through main relay

Matthew Kennedy  4:53 AM
ok
4:53
it probably does need the diode though
4:53
it active clamps, but that's very different for a fine-control solenoid like this

CrazyStriker  4:53 AM
It definitely needs the diode. It has been specified since frankenso

andreika  4:53 AM
AUIPS2041 has a pretty decent active clamp, I tried to kill it but couldn't

CrazyStriker  4:54 AM
Diode for VVT and idle valve

Matthew Kennedy  4:54 AM
@andreika the point is not that you'll hurt the chip (I don't think it will), but that you want nice linear current control

CrazyStriker  4:54 AM
At the cost of diodes it doesn't hurt to put on a big one. I did for the NB2 PnP board

Matthew Kennedy  4:54 AM
active clamp's job is to collapse the field as fast as possible
4:54
we want to maintain field as long as possible

andreika  4:56 AM
good point. Maybe we should add it
4:57
And for idle solenoid too, yep

CrazyStriker  4:59 AM
If you can put one on next rev it would be cool, for idle too

andreika  5:00 AM
sure

CrazyStriker  5:00 AM
In the meantime I can bodge one big unit on each
5:00
Between +12 and output

**Comment by CrazyStriker** [comment]
Temporary bodge 

![IMG_20210506_192121](https://user-images.githubusercontent.com/38209146/117421169-95151a80-af1e-11eb-893a-d9ea0109c26f.jpg)
![IMG_20210506_192803](https://user-images.githubusercontent.com/38209146/117421190-99d9ce80-af1e-11eb-9716-d07e980c73a6.jpg)

I can confirm IAC and VVT are now working as expected
