### ISSUE TITLE
Hellen64 No Silkscreen ID for jumpers

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [andreika-git/hellen-one#41]
Previously the MRE48 pnp and Hellen72 had Jumper IDs printed on the board for quick and Easy Identification. H64 does not have those. Picture below is example.

![No JP ID](https://user-images.githubusercontent.com/82395131/117235713-3c962e00-adf5-11eb-99e6-f8da911717b8.jpg)

**Comment by Qwerty-OFF** [comment]
Designators is disabled in the export settings guide. We need to add silk manually or enable designators
https://github.com/andreika-git/hellen-one/wiki/kicad-export-frame
![image](https://user-images.githubusercontent.com/4116383/117277871-eb278680-ae68-11eb-97e2-a3da895a81f5.png)

**Comment by rusefillc** [comment]
I assume this is done
