### ISSUE TITLE
don't use LEDs as a pullup

### ISSUE THREAD

**Issue by mck1117** [andreika-git/hellen-one#42]
If you want an LED and a pullup, wire both.  Do not rely on the LED as a pullup.  Using the LED in series with the pullup may not have the desired effect.

For example, in the VR module:

![image](https://user-images.githubusercontent.com/568254/117245281-6fd5be80-adef-11eb-8224-61bc68efca61.png)

**Comment by andreika-git** [comment]
We do not rely on LED resistors for pull-ups. We do have pull-ups in both input and dinput4 modules (for all required inputs including VR):
![image](https://user-images.githubusercontent.com/15104768/117257337-70ed0700-ae54-11eb-835c-904feceba01c.png)

**Comment by mck1117** [comment]
Then what's going on in the VR module?

![image](https://user-images.githubusercontent.com/568254/117258852-470af480-ae02-11eb-97ea-30e16501d56c.png)

**Comment by andreika-git** [comment]
What exactly is wrong in the VR module? The "true" pull-up resistors are not in the VR module, they are in the input module because the VR module is not the only source of VR signal - Hellen One has a working software VR processing capability.

**Comment by mck1117** [comment]
> The "true" pull-up resistors are not in the VR module

this is antithetical to the whole point of a modular design

> VR module is not the only source of VR signal

If you are suggesting connecting more than one source to the same net (then connecting to a single MCU pin), why? We can switch inputs in software.  One source.  One sink.  One pullup, located on the schematic of the SOURCE.

> Hellen One has a working software VR processing capability

I'll believe it when I see it

**Comment by mck1117** [comment]
this has now caused confusion in #49 - this module really does need internal pullup so that use of an extra module isn't needed.
