### ISSUE TITLE
[sd] add decoupling cap for SD card

### ISSUE THREAD

**Issue by mck1117** [andreika-git/hellen-one#45]
SD card should have a decoupling cap across the power rails near the socket.  I've heard stories (not our boards) of people having SD card unreliability due to no decoupling caps near the card.

**Comment by andreika-git** [comment]
We already have more than enough decoupling caps for the sd card on the sd module:
![image](https://user-images.githubusercontent.com/15104768/117255303-28cce500-ae52-11eb-9dcf-660fc57c3171.png)
![image](https://user-images.githubusercontent.com/15104768/117255509-66ca0900-ae52-11eb-8e8f-864332ee1357.png)

**Comment by mck1117** [comment]
Apparently my eyes can't read the monochrome schematics from Altium.

22u is pretty big.  Absolutely worth replacing one of the 22u with a 1u or even 100n.
