### ISSUE TITLE
PWM vr-interface module

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#49]
Let's try https://github.com/mck1117/vr-interface as an untested-on-real-vehicle alternative to MAX9926 VR conditioner

Is that vr-interface large enough for a module or do we copy/paste it as is?

**Comment by rusefillc** [comment]
@mck1117 would you be interested to practice your Hellen module skills?

**Comment by mck1117** [comment]
I think it warrants a module, yes.  Go ahead and assign to me.

**Comment by rusefillc** [comment]
I am hoping that we are 1 week from sending hellen-mercedes to the fab. I guess technically we can totally skip PWM vr-interface in rev A but see what you can do please?

**Comment by mck1117** [comment]
yes, that looks OK to me.  The unwritten (in the schematic) part of the NOR gate that we need is that it must allow you to sink current out of the input pins - using the diode from GND -> input.  However, the replacement chip allows this in the datasheet, so everything looks OK.

**Comment by rusefillc** [comment]
@mck1117 which of the three outputs do we want to feed into Hellen?

![image](https://user-images.githubusercontent.com/48498823/118172526-7caf6f00-b3fa-11eb-88dc-6783bb3aba1c.png)

**Comment by mck1117** [comment]
"Output" = digital output, conditioned VR signal, actual trigger input.
"Analog out" = if we want an oscilloscope trace of the trigger
"Thresh in" = pwm output from stm32

**Comment by rusefillc** [comment]
sounds like "Analog out" is good to have a via on the PCB for just in case but not route to MCU

**Comment by mck1117** [comment]
I want to route it to ADC3 so we can do this: http://www.maxxecu.com/webhelp/settings-diagnostics-trigger_oscilloscope.html

**Comment by rusefillc** [comment]
The knock ADC3? :)

**Comment by mck1117** [comment]
Yes, that ADC3 🙂

We don't ever need knock and trigger scope at the same time.  Trigger scope with some free revving to check the trigger threshold, then knock once you're actually driving around.

**Comment by rusefillc** [comment]
@Qwerty-OFF @andreika-git  ^^^

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/118182368-96c07000-b441-11eb-8f1c-6e80e4af595c.png)
Is it ok?

**Comment by mck1117** [comment]
@andreika-git does `vr-0.1` need external pullup resistor? This is exactly the confusion in #42.

**Comment by mck1117** [comment]
@andreika-git ping

**Comment by andreika-git** [comment]
> 
> Is it ok?

Yes, it's ok, no additional pullups needed.

**Comment by mck1117** [comment]
No pullup or not? Because in #42 you said the VR module requires an external pullup.

**Comment by andreika-git** [comment]
I didn't say anything about "external" pullup. I said that the required pullup for crank-vr input is already in the respective module. No additional pullups required for the schematics done by @Qwerty-OFF.

**Comment by rusefillc** [comment]
Created!
