### ISSUE TITLE
opamps should prefer MCP6004

### ISSUE THREAD

**Issue by mck1117** [andreika-git/hellen-one#63]
TSSOP14 opamps should prefer MCP6004T-I/ST (C50282) over LMV324, as the DC performance of the MCP is better.  In particular, the LMV can't get within ~0.5v of the positive rail, which is required for some OEM TPS sensors (et al)

**Comment by rusefillc** [comment]
See #27

**Comment by rusefillc** [comment]
We need new revisions of both Hellen MCU 144 and 176 with C398929 and LMV324 completely wiped out TODAY

Very disappointing that we have not handles this better and now we have at least 10 boards full of LMV324, this was very preventable.

**Comment by andreika-git** [comment]
https://github.com/andreika-git/hellen-one/commit/6e68005fa9b13a718671ad632f19f5b2b39c0ed1

**Comment by andreika-git** [comment]
Another advantage is that MCP6004T can withstand up to -1V negative input, but LMV324 is limited to only -0.2V, which is less than SRV05-4 limiter can guarantee. LMV324 saturates output for even slightly negative input voltages.

**Comment by mck1117** [comment]
lmv even saturates the output with 0v input
