### ISSUE TITLE
Chip Shortage: Transceiver CAN

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#72]
TJA1051T/3/1J https://lcsc.com/product-detail/CAN-ICs_NXP-Semicon-TJA1051T-3-1J_C38695.html says bye-bye

@mck1117 says MCP2551T-I/SN https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=C49558

![image](https://user-images.githubusercontent.com/48498823/122689871-dc681980-d1f3-11eb-833c-f10e8cf82676.png)

**Comment by rusefillc** [comment]
@mck1117 is mcp2551 pin compatible?

**Comment by rusefillc** [comment]
@andreika-git @qwerty-off

![image](https://user-images.githubusercontent.com/48498823/122690082-5f3da400-d1f5-11eb-9eb0-4298707a4894.png)

**Comment by rusefillc** [comment]
@mck1117 says
C49558 That's what's on latest proteus
Works fine
Used to have tja

**Comment by Qwerty-OFF** [comment]
The MCP2551 has no Vio pin. Is our STM32 5V-tolerant on CAN_RX pin?

**Comment by mck1117** [comment]
yes
