### ISSUE TITLE
inconsistent DFU 

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#79]
We have reports of two or three kinds of Hellen boards failing to reboot into DFU via "reboot_dfu" command

Same reboot to DFU procedure could be initiated by rusEFI console using "Program" button while "Automatic DFU" is selected

This issue is NOT about "reset" or "PROD" button, the scope of this issue is ONLY software-based reboot to DFU

Steps to reproduce:
1) have a Hellen board with 407 chip
2) have Hellen board with 407 blink blue LED
3) connect via USB
4) hit "automatic DFU" in rusEFI console

expected result: DFU process starts

actual result: board reboots into normal operation

**Comment by BeerMoneyMotorsports** [comment]
Auto DFU tests USB power only

H72c w/F429- Pass-5 Fail- 0
H64a w/F407- Pass-0 Fail- 5
H64b w/f407- Pass-1 Fail- 4

![image](https://user-images.githubusercontent.com/82395131/125209890-1fa12f80-e26a-11eb-8beb-39b75d750314.png)

**Comment by BeerMoneyMotorsports** [comment]
H72c
![44E61158-3E2E-489E-A862-68E442BA196B](https://user-images.githubusercontent.com/82395131/125210021-09e03a00-e26b-11eb-9ced-fb88b16db5fe.jpeg)

H64a
![804E2C99-916D-4B13-805A-3563D00B196A](https://user-images.githubusercontent.com/82395131/125210039-1fedfa80-e26b-11eb-9e2e-d814f03b7013.jpeg)

H64b
![5E097665-61C8-412F-9E22-09F75DF5B98F](https://user-images.githubusercontent.com/82395131/125210047-2f6d4380-e26b-11eb-915b-05b978abe807.jpeg)

**Comment by rusefillc** [comment]
![IMG_20210711_185521](https://user-images.githubusercontent.com/48498823/125212276-3baccd00-e27a-11eb-9aeb-44df3694e939.jpg)

not hellen with old 407 SW dfu jump works!

that's inconclusive

i also have 2nd 176 407 from same pack of samples

that opens many possibilities but i would compare designs arounds caps etc before we go swapping parts

maybe up some caps?

@dron0gus

**Comment by mck1117** [comment]
With the PROG button held (ie, MCU always enters system ROM at reset), the reset line is triggering every exactly 1 second, so something is triggering a hardware reset after ~1 second 

Reset is low, not reset is high:

![SDS00044](https://user-images.githubusercontent.com/568254/125228608-eed0f280-e289-11eb-9ff6-4522166bee3e.png)

The large period at the left is me pressing the physical reset button, then the ~1 second spaced blips are the MCU resetting itself.

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/125228831-5c7d1e80-e28a-11eb-8b43-be6ff6598c20.png)

**Comment by mck1117** [comment]
When attaching a debugger to a completely blank chip when boot looping the bootloader, it says the software reset bit is set in RCC register CSR.

![image](https://user-images.githubusercontent.com/568254/125230058-e3cb9180-e28c-11eb-8882-4949569d73a7.png)

**Comment by mck1117** [comment]
Here are an old MRE (f407), f4 disco, and hellen probed at the OSCOUT (PH1) pin:

hellen:

![SDS00046](https://user-images.githubusercontent.com/568254/125231530-cc41d800-e28f-11eb-892a-390d9de7ff7d.png)

microRusEfi:

![SDS00045](https://user-images.githubusercontent.com/568254/125231519-c6e48d80-e28f-11eb-85c6-343da41ed08f.png)

F4 discovery:

![SDS00047](https://user-images.githubusercontent.com/568254/125231677-0ca15600-e290-11eb-80fb-0622ae72cddd.png)

**Comment by rusefillc** [comment]
OMG

![Image from iOS (4)](https://user-images.githubusercontent.com/48498823/125232931-a32f4080-e2ab-11eb-8f27-1d7382e9df9f.jpg)

**Comment by rusefillc** [comment]
```
I replaced $0.2 part with a "crystal and caps" that is guaranteed to oscillate well within the allotted time (edited) 
the bootloader waits 800us for the clock to start
if the clock doesn't start in 800us, it triggers a system reset
our clock is locking in ~900us or so
```

**Comment by mck1117** [comment]
The above photo is injecting an 8mhz sine wave in to the OSC_IN pin - so that we can guarantee the "crystal" will have locked

**Comment by mck1117** [comment]
Evidently the F42x bootloader waits longer, because on a random proteus board it takes even longer, but the bootloader still works perfectly

**Comment by mck1117** [comment]
With the F407 discovery's oscillator transplanted on to the hellen121a PCB:

![SDS00049](https://user-images.githubusercontent.com/568254/125236668-3e6aea80-e299-11eb-8a44-9908aeb1f7ea.png)

**Comment by andreika-git** [comment]
There are some JLC drop-in alternatives to consider: 
* C122522
* C172361
* C111120
* C90881

**Comment by andreika-git** [comment]
Here's a similar topic already discussed:
https://community.st.com/s/question/0D53W000004lc5NSAQ/dfu-over-usb-not-working-hse-not-detected

**Comment by mck1117** [comment]
This will add support for alternate crystal speeds without different firmware: https://github.com/rusefi/rusefi/pull/2952

**Comment by rusefillc** [comment]
520-200-12-30-AEM-TR

**Comment by rusefillc** [comment]
Maybe this is linked to the embedded bootloader version:

V3 on STM32F407 and STM32F401
V7 on STM32F427
V9 on STM32F446

Check AN2606 for details


https://www.st.com/resource/en/application_note/cd00167594-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics.pdf

**Comment by rusefillc** [comment]
digikey stuff in stock


H130A-8.000-8-2030-TR‎ 8 MHz
‎2845-WTL5G60390VH-ND‎ 8 MHz
535-9105-1-ND (20 MHz ESR 30 Ohm)
CTX1436CT-ND (16 MHz, ESR 40 Ohm)
644-1037-1-ND (16 MHz, ESR 120 Ohm)

**Comment by mck1117** [comment]
Ordered a stack of 16 and 20MHz options from digikey, will test soon on 121vw

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports please order qty 20 of 

ABM3-20.000MHZ-B2-T  535-9105-1-ND 20 MHz ESR 30 Ohm

I believe that we have major improvement in Hellen72 rev D behavior

**Comment by rusefillc** [comment]
@mck1117 says that 20MHz crystal ABM3-20.000MHZ-B2-T starts in ~250us

looks like minimal fix for Hellen MCU is to jump from 8MHz to 20MHz and move on?

@andreika-git @mck1117
