### ISSUE TITLE
Test mini-USB adapter board for Hellen72

### ISSUE THREAD

**Issue by andreika-git** [andreika-git/hellen-one#9]
We have an alternative USB routed for a small adapter board near the main ECU connector. We need to test it:
- does it fit at all?
- does it work?
- can we still use both USB connectors or they interfere with each other?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/108587815-ea7c5b00-7323-11eb-962e-aef8f01a5a43.png)

**Comment by rusefillc** [comment]
@andreika-git what do you mean "can we still use both USB connectors or they interfere with each other?"

two cables into same PC? two cables at the same time into different PCs?

**Comment by andreika-git** [comment]
Not two cables, but just one cable into any of two connectors without desoldering them

**Comment by rusefillc** [comment]
that works
