### ISSUE TITLE
WBO module: through-hole option for MOSFET

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#97]
JLC does not have SMD WBO MOSFET options, let's make module dual-option with through-hole

@mck1117 FYI if you would be interested to back-port into original module

**Comment by rusefillc** [comment]
closed by https://github.com/andreika-git/hellen-one/commit/fbb81e625d6785b877d6fde05a8ff4b707ec4615

**Comment by rusefillc** [comment]
VNP28N04-E (C263002) is a candidate

**Comment by mck1117** [comment]
euh, I don't really like through hole.  Big vibration problems with a TO220 flapping around.
